spring:
  application:
    name: auth-service
  devtools:
    restart:
      enabled: ${DEVTOOLS}
      additional-paths:
        - .
    livereload:
      enabled: ${DEVTOOLS}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

owner:
  name: ${OWNER_NAME}
  password: ${OWNER_PASSOWORD}


logging:
  level:
    root: ${LOGGING_LEVEL}

server:
  port: 8083
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include:
          - health
