spring:
  application:
    name: api-service
  devtools:
    restart:
      enabled: true
      additional-paths:
        - .
    livereload:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

logging:
  level:
    root: DEBUG

server:
  port: 8081