services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./gateway/src/main:/wd/gateway/src/main
      - ./shared/src/main:/wd/shared/src/main
      - ./target:/wd/target
    restart: no
    environment:
      - API_URL=http://api-service:8081
      - FRONTEND_URL=http://frontend-service:8082
      - AUTH_URL=http://auth-service:8083
      - KEY_STORE=$KEY_STORE
      - KEY_PASSWORD=$KEY_PASSWORD
      - KEY_ALIAS=$KEY_ALIAS
    depends_on:
      - frontend-service
      - api-service
    networks:
      - blog-net

  frontend-service:
    container_name: frontend-service
    build:
      context: .
      dockerfile: frontend-service/Dockerfile
    ports:
      - 8082:8082
    volumes:
      - ./frontend-service/src/main:/wd/frontend-service/src/main
      - ./shared/src/main:/wd/shared/src/main
      - ./target:/wd/target
    restart: no
    environment:
      - GATEWAY_URL=http://gateway:8080
    depends_on:
      - api-service
    networks:
      - blog-net

  api-service:
    container_name: api-service
    build:
      context: .
      dockerfile: api-service/Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./api-service/src/main:/wd/api-service/src/main
      - ./shared/src/main:/wd/shared/src/main
      - ./target:/wd/target
    restart: no
    environment:
      - SPRING_DATASOURCE_URL=$DB_URL
      - SPRING_DATASOURCE_USERNAME=$DB_USER
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - database
    networks:
      - blog-net

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - 8083:8083
    volumes:
      - ./auth-service/src/main:/wd/auth-service/src/main
      - ./shared/src/main:/wd/shared/src/main
      - ./target:/wd/target
    restart: no
    environment:
      - OWNER_NAME=$OWNER_NAME
      - OWNER_PASSWORD=$OWNER_PASSWORD
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRATION=$JWT_EXPIRATION
    networks:
      - blog-net

  database:
    container_name: database
    image: 'postgres:17'
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    networks:
      - blog-net

networks:
  blog-net: