spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: true
      additional-paths:
        - .
    livereload:
      enabled: true


server:
  port: 8080
  ssl:
    enabled: true
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${KEY_ALIAS}

logging:
  level:
    root: DEBUG

services:
  api: ${API_URL}
  frontend: ${FRONTEND_URL}
  auth: ${AUTH_URL}
