spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: true
      additional-paths:
        - .
    livereload:
      enabled: true


server:
  port: 8080

logging:
  level:
    root: DEBUG

services:
  api: ${API_URL}
  frontend: ${FRONTEND_URL}
  auth: ${AUTH_URL}
