spring:
  application:
    name: gateway
  devtools:
    restart:
      enabled: ${DEVTOOLS}
      additional-paths:
        - .
    livereload:
      enabled: ${DEVTOOLS}


server:
  port: 8080

logging:
  level:
    root: ${LOGGING_LEVEL}

services:
  api: ${API_URL}
  frontend: ${FRONTEND_URL}
  auth: ${AUTH_URL}
