spring:
  application:
    name: frontend-service
  devtools:
    restart:
      enabled: ${DEVTOOLS}
      additional-paths:
        - .
    livereload:
      enabled: ${DEVTOOLS}

logging:
  level:
    root: ${LOGGING_LEVEL}

server:
  port: 8082
  error:
    include-stacktrace: never

services:
  api: ${GATEWAY_URL}

springdoc:
  swagger-ui:
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include:
          - health
