spring:
  application:
    name: frontend-service
  devtools:
    restart:
      enabled: true
      additional-paths:
        - .
    livereload:
      enabled: true

server:
  port: 8080

services:
  api: ${API_URL}