spring:
  application:
    name: frontend-service
  devtools:
    restart:
      enabled: ${DEVTOOLS}
      additional-paths:
        - .
    livereload:
      enabled: ${DEVTOOLS}

logging:
  level:
    root: ${LOGGING_LEVEL}

server:
  port: 8082

services:
  api: ${GATEWAY_URL}