
apiVersion: v1
kind: Pod
metadata: 
  name: database-pod
  labels:
    app: database-app
spec:
  containers:
    - name: database
      image: postgres:17
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: DB_PASSWORD
      volumeMounts:
        - name: database-data
          mountPath: /data/database

  volumes:
    - name: database-data
      persistentVolumeClaim:
        claimName: database-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
