apiVersion: v1
kind: Pod
metadata: 
  name: frontend-pod
  labels:
    app: frontend-app
spec:
  containers:
    - name: frontend-service
      image: ghcr.io/rykktiadloans/blog-frontend-service:v1.0.0
      ports:
        - containerPort: 8082
      env:
        - name: LOGGING_LEVEL
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: LOGGING_LEVEL
        - name: DEVTOOLS
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: DEVTOOLS

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
