apiVersion: v1
kind: Pod
metadata: 
  name: gateway-pod
  labels:
    app: gateway-app
spec:
  containers:
    - name: gateway-service
      image: ghcr.io/rykktiadloans/blog-gateway:v1.0.0
      ports:
        - containerPort: 8080
      env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: API_URL
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: AUTH_URL
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: FRONTEND_URL
        - name: LOGGING_LEVEL
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: LOGGING_LEVEL
        - name: DEVTOOLS
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: DEVTOOLS

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.org/ssl-services: “eclwatch"
    nginx.ingress.kubernetes.io/limit-rps: "10"

spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http: 
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 8080
