name: Publish Docker containers

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build API service
        run: ./gradlew api-service:bootBuildImage --imageName=${{ env.REGISTRY }}/rykktiadloans/blog-api-service:${{ github.ref_name }} -x api-service:test

      - name: DEBUG - docker images
        run: docker images

      - name: Push API service
        run: docker push ${{ env.REGISTRY }}/rykktiadloans/blog-api-service:${{ github.ref_name }}
